### ISSUE TITLE
QuantClientEndpoint empty data object

### ISSUE THREAD

**Issue by a-o-can** [cyyever/distributed_learning_simulator#7]
Hello there,

I am trying to reproduce the experiments for FedOBD as stated in the readme for the datasets CIFAR10 and CIFAR100. I made sure to have installed the datasets, however I faced the following assertion error:

 File "/home/<myUserName>/Projects/distributed_learning_simulator/simulation_lib/topology/quantized_endpoint.py", line 25, in get
    assert isinstance(data, ParameterMessage)
AssertionError
2024-03-02T19:48:15Z <Greenlet at 0x7f5960075440: <bound method Worker.start of <simulation_lib.method.fed_obd.worker.FedOBDWorker object at 0x7f5956373800>>> failed with AssertionError

for every FedOBD Worker. Upon debugging, the problem lies in the function simulation_lib/topology/quantized_endpoint.py/QuantClientEndpoint->get(). Specifically the data=super().get() in line 22 returns a None and it gets caught by the assertion in line 25 for not being of class ParameterMessage. Is this already a known issue or does it lie within my process solely? Are there any suggestions from your side? @cyyever 

Best
-A

**Comment by cyyever** [comment]
@a-o-can Can you git pull the latest simulator code? I just fixed the bug which was introduced in recent refactoring. The test scripts passed on my host.

**Comment by a-o-can** [comment]
Thanks for the prompt reply. The config name in the fed_obd_train.sh expects a folder for fed_obd in the large_scale folder, which does not exist. Copying the fed_obd folder with the yaml files from the parent conf folder into the large_scale folder solves the previous assertion error, i.e. data is now being read correctly from super().get(). However, the code still does not run correctly due to a further error while starting the workers. Specifically in the function simulation_lib/worker/worker.py/Worker/->start() the line 74 throws an error, where self.trainer.set_device_fun() is called. The trainer object does not have the function set_device_fun(). The closest function (based on the name) is trainer.set_device(), which also causes further error. @cyyever

**Comment by cyyever** [comment]
@a-o-can Due to recent refactoring, let's assume that you use pip, then you should remove cyy_torch_toolbox  and install the latest version as follows:
```
pip3 uninstall cyy_torch_toolbox          
pip3 install git+ssh://git@github.com/cyyever/torch_toolbox.git@main#egg=cyy_torch_toolbox                  --user
``` 
And the bash file was also changed to use the new config files.

**Comment by a-o-can** [comment]
Seems to be running now. Thank you!
